### PR TITLE
Switch to rho-contracts-fork

### PR DESCRIPTION
**Pull request by paulmelnikow**

### CODE REVIEW

**Comment by maxdumas** [comment]
LGTM once the new version of `rho-cc-bucket-name` is published and this build is passing.

**Comment by paulmelnikow** [comment]
Should this be a major or a patch?

We've been treating the library updates as major, since they require a different dependency than before. Here that's not really the case. However, a project using urj that is sharing any dependencies will also need to update those dependencies.

I'm leaning toward patch.

**Comment by maxdumas** [comment]
I'm fine with patch also.

**Comment by paulmelnikow** [comment]
Sounds good, thanks.

**Pull request merged**
