### PR TITLE
Fix lingering references to rho-contracts

### PR DESCRIPTION
**Pull request by paulmelnikow**

### CODE REVIEW

**Comment by maxdumas** [comment]
Looks like the problem percolates down into `rho-cc-s3-bucket-name`, which still has references to `rho-contracts`. That'll need to be fixed before this.

**Comment by gmarceau** [comment]
👍

**Comment by paulmelnikow** [comment]
@maxdumas Yeah, I fixed that one too, but I guess forgot to open the PR: bodylabs/rho-cc-s3-bucket-name#5.

**Comment by maxdumas** [comment]
👍 Once build is passing

**Pull request merged**
